const API_KEY = process.env.CRYPTO_API_KEY;

export async function GET(request: Request) {
    // const ids = new URL(request.url).searchParams.get('ids');

    // const response = await fetch(
    //     `https://pro-api.coinmarketcap.com/v2/cryptocurrency/info?id=${ids}`,
    //     {
    //         headers: {
    //             'X-CMC_PRO_API_KEY': API_KEY!,
    //         },
    //     }
    // );

    // const res = await response.json();
    // return Response.json(res.data);
    return Response.json(mockData);
}

const mockData = {
    '1': {
        id: 1,
        name: 'Bitcoin',
        symbol: 'BTC',
        category: 'coin',
        description:
            'Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,698,365. The last known price of Bitcoin is 61,549.57809675 USD and is down -2.17 over the last 24 hours. It is currently trading on 11045 active market(s) with $28,187,032,546.83 traded over the last 24 hours. More information can be found at https://bitcoin.org/.',
        slug: 'bitcoin',
        logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1.png',
        subreddit: 'bitcoin',
        notice: '',
        tags: [
            'mineable',
            'pow',
            'sha-256',
            'store-of-value',
            'state-channel',
            'coinbase-ventures-portfolio',
            'three-arrows-capital-portfolio',
            'polychain-capital-portfolio',
            'binance-labs-portfolio',
            'blockchain-capital-portfolio',
            'boostvc-portfolio',
            'cms-holdings-portfolio',
            'dcg-portfolio',
            'dragonfly-capital-portfolio',
            'electric-capital-portfolio',
            'fabric-ventures-portfolio',
            'framework-ventures-portfolio',
            'galaxy-digital-portfolio',
            'huobi-capital-portfolio',
            'alameda-research-portfolio',
            'a16z-portfolio',
            '1confirmation-portfolio',
            'winklevoss-capital-portfolio',
            'usv-portfolio',
            'placeholder-ventures-portfolio',
            'pantera-capital-portfolio',
            'multicoin-capital-portfolio',
            'paradigm-portfolio',
            'bitcoin-ecosystem',
            'ftx-bankruptcy-estate',
        ],
        'tag-names': [
            'Mineable',
            'PoW',
            'SHA-256',
            'Store Of Value',
            'State Channel',
            'Coinbase Ventures Portfolio',
            'Three Arrows Capital Portfolio',
            'Polychain Capital Portfolio',
            'Binance Labs Portfolio',
            'Blockchain Capital Portfolio',
            'BoostVC Portfolio',
            'CMS Holdings Portfolio',
            'DCG Portfolio',
            'DragonFly Capital Portfolio',
            'Electric Capital Portfolio',
            'Fabric Ventures Portfolio',
            'Framework Ventures Portfolio',
            'Galaxy Digital Portfolio',
            'Huobi Capital Portfolio',
            'Alameda Research Portfolio',
            'a16z Portfolio',
            '1Confirmation Portfolio',
            'Winklevoss Capital Portfolio',
            'USV Portfolio',
            'Placeholder Ventures Portfolio',
            'Pantera Capital Portfolio',
            'Multicoin Capital Portfolio',
            'Paradigm Portfolio',
            'Bitcoin Ecosystem',
            'FTX Bankruptcy Estate ',
        ],
        'tag-groups': [
            'OTHERS',
            'ALGORITHM',
            'ALGORITHM',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'PLATFORM',
            'CATEGORY',
        ],
        urls: {
            website: [Array],
            twitter: [],
            message_board: [Array],
            chat: [],
            facebook: [],
            explorer: [Array],
            reddit: [Array],
            technical_doc: [Array],
            source_code: [Array],
            announcement: [],
        },
        platform: null,
        date_added: '2010-07-13T00:00:00.000Z',
        twitter_username: '',
        is_hidden: 0,
        date_launched: '2010-07-13T00:00:00.000Z',
        contract_address: [],
        self_reported_circulating_supply: null,
        self_reported_tags: null,
        self_reported_market_cap: null,
        infinite_supply: false,
    },
    '825': {
        id: 825,
        name: 'Tether USDt',
        symbol: 'USDT',
        category: 'token',
        description:
            'Tether USDt (USDT) is a cryptocurrency and operates on the Ethereum platform. Tether USDt has a current supply of 113,086,550,460.855 with 110,846,923,650.03687 in circulation. The last known price of Tether USDt is 0.99959453 USD and is down -0.02 over the last 24 hours. It is currently trading on 85475 active market(s) with $57,382,654,997.10 traded over the last 24 hours. More information can be found at https://tether.to.',
        slug: 'tether',
        logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/825.png',
        subreddit: '',
        notice: '',
        tags: [
            'stablecoin',
            'asset-backed-stablecoin',
            'avalanche-ecosystem',
            'solana-ecosystem',
            'arbitrum-ecosytem',
            'moonriver-ecosystem',
            'injective-ecosystem',
            'bnb-chain',
            'usd-stablecoin',
            'optimism-ecosystem',
            'fiat-stablecoin',
        ],
        'tag-names': [
            'Stablecoin',
            'Asset-Backed Stablecoin',
            'Avalanche Ecosystem',
            'Solana Ecosystem',
            'Arbitrum Ecosystem',
            'Moonriver Ecosystem',
            'Injective Ecosystem',
            'BNB Chain',
            'USD Stablecoin',
            'Optimism Ecosystem',
            'Fiat Stablecoin',
        ],
        'tag-groups': [
            'CATEGORY',
            'CATEGORY',
            'PLATFORM',
            'PLATFORM',
            'PLATFORM',
            'PLATFORM',
            'PLATFORM',
            'PLATFORM',
            'CATEGORY',
            'PLATFORM',
            'CATEGORY',
        ],
        urls: {
            website: [Array],
            twitter: [Array],
            message_board: [],
            chat: [Array],
            facebook: [],
            explorer: [Array],
            reddit: [],
            technical_doc: [Array],
            source_code: [],
            announcement: [Array],
        },
        platform: {
            id: '1027',
            name: 'Ethereum',
            slug: 'ethereum',
            symbol: 'ETH',
            token_address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
        },
        date_added: '2015-02-25T00:00:00.000Z',
        twitter_username: 'tether_to',
        is_hidden: 0,
        date_launched: null,
        contract_address: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        self_reported_circulating_supply: null,
        self_reported_tags: null,
        self_reported_market_cap: null,
        infinite_supply: true,
    },
    '1027': {
        id: 1027,
        name: 'Ethereum',
        symbol: 'ETH',
        category: 'coin',
        description:
            'Ethereum (ETH) is a cryptocurrency . Ethereum has a current supply of 120,114,986.95090629. The last known price of Ethereum is 2,881.01433388 USD and is down -2.35 over the last 24 hours. It is currently trading on 8926 active market(s) with $12,444,897,732.57 traded over the last 24 hours. More information can be found at https://www.ethereum.org/.',
        slug: 'ethereum',
        logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
        subreddit: 'ethereum',
        notice: '',
        tags: [
            'pos',
            'smart-contracts',
            'ethereum-ecosystem',
            'coinbase-ventures-portfolio',
            'three-arrows-capital-portfolio',
            'polychain-capital-portfolio',
            'binance-labs-portfolio',
            'blockchain-capital-portfolio',
            'boostvc-portfolio',
            'cms-holdings-portfolio',
            'dcg-portfolio',
            'dragonfly-capital-portfolio',
            'electric-capital-portfolio',
            'fabric-ventures-portfolio',
            'framework-ventures-portfolio',
            'hashkey-capital-portfolio',
            'kenetic-capital-portfolio',
            'huobi-capital-portfolio',
            'alameda-research-portfolio',
            'a16z-portfolio',
            '1confirmation-portfolio',
            'winklevoss-capital-portfolio',
            'usv-portfolio',
            'placeholder-ventures-portfolio',
            'pantera-capital-portfolio',
            'multicoin-capital-portfolio',
            'paradigm-portfolio',
            'injective-ecosystem',
            'layer-1',
            'ftx-bankruptcy-estate',
        ],
        'tag-names': [
            'PoS',
            'Smart Contracts',
            'Ethereum Ecosystem',
            'Coinbase Ventures Portfolio',
            'Three Arrows Capital Portfolio',
            'Polychain Capital Portfolio',
            'Binance Labs Portfolio',
            'Blockchain Capital Portfolio',
            'BoostVC Portfolio',
            'CMS Holdings Portfolio',
            'DCG Portfolio',
            'DragonFly Capital Portfolio',
            'Electric Capital Portfolio',
            'Fabric Ventures Portfolio',
            'Framework Ventures Portfolio',
            'Hashkey Capital Portfolio',
            'Kenetic Capital Portfolio',
            'Huobi Capital Portfolio',
            'Alameda Research Portfolio',
            'a16z Portfolio',
            '1Confirmation Portfolio',
            'Winklevoss Capital Portfolio',
            'USV Portfolio',
            'Placeholder Ventures Portfolio',
            'Pantera Capital Portfolio',
            'Multicoin Capital Portfolio',
            'Paradigm Portfolio',
            'Injective Ecosystem',
            'Layer 1',
            'FTX Bankruptcy Estate ',
        ],
        'tag-groups': [
            'ALGORITHM',
            'CATEGORY',
            'PLATFORM',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'PLATFORM',
            'CATEGORY',
            'CATEGORY',
        ],
        urls: {
            website: [Array],
            twitter: [Array],
            message_board: [Array],
            chat: [Array],
            facebook: [],
            explorer: [Array],
            reddit: [Array],
            technical_doc: [Array],
            source_code: [Array],
            announcement: [Array],
        },
        platform: null,
        date_added: '2015-08-07T00:00:00.000Z',
        twitter_username: 'ethereum',
        is_hidden: 0,
        date_launched: null,
        contract_address: [
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
            [Object],
        ],
        self_reported_circulating_supply: null,
        self_reported_tags: null,
        self_reported_market_cap: null,
        infinite_supply: true,
    },
    '1839': {
        id: 1839,
        name: 'BNB',
        symbol: 'BNB',
        category: 'coin',
        description:
            'BNB (BNB) is a cryptocurrency . BNB has a current supply of 147,586,676.0877253. The last known price of BNB is 566.69551022 USD and is down -4.21 over the last 24 hours. It is currently trading on 2159 active market(s) with $1,944,362,713.28 traded over the last 24 hours. More information can be found at https://bnbchain.org/en.',
        slug: 'bnb',
        logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png',
        subreddit: 'bnbchainofficial',
        notice: '',
        tags: [
            'marketplace',
            'centralized-exchange',
            'payments',
            'smart-contracts',
            'alameda-research-portfolio',
            'multicoin-capital-portfolio',
            'bnb-chain',
            'layer-1',
            'sec-security-token',
            'alleged-sec-securities',
            'celsius-bankruptcy-estate',
        ],
        'tag-names': [
            'Marketplace',
            'Centralized Exchange (CEX) Token',
            'Payments',
            'Smart Contracts',
            'Alameda Research Portfolio',
            'Multicoin Capital Portfolio',
            'BNB Chain',
            'Layer 1',
            'SEC Security Token',
            'Alleged SEC Securities',
            'Celsius Bankruptcy Estate',
        ],
        'tag-groups': [
            'INDUSTRY',
            'CATEGORY',
            'INDUSTRY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'PLATFORM',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
        ],
        urls: {
            website: [Array],
            twitter: [Array],
            message_board: [],
            chat: [Array],
            facebook: [],
            explorer: [Array],
            reddit: [Array],
            technical_doc: [],
            source_code: [Array],
            announcement: [],
        },
        platform: null,
        date_added: '2017-07-25T00:00:00.000Z',
        twitter_username: 'bnbchain',
        is_hidden: 0,
        date_launched: null,
        contract_address: [[Object]],
        self_reported_circulating_supply: null,
        self_reported_tags: null,
        self_reported_market_cap: null,
        infinite_supply: false,
    },
    '5426': {
        id: 5426,
        name: 'Solana',
        symbol: 'SOL',
        category: 'coin',
        description:
            'Solana (SOL) is a cryptocurrency launched in 2020. Solana has a current supply of 576,014,306.8080466 with 448,648,862.2486471 in circulation. The last known price of Solana is 142.02613506 USD and is down -3.61 over the last 24 hours. It is currently trading on 660 active market(s) with $2,586,238,516.00 traded over the last 24 hours. More information can be found at https://solana.com.',
        slug: 'solana',
        logo: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
        subreddit: 'solana',
        notice: '',
        tags: [
            'pos',
            'platform',
            'solana-ecosystem',
            'cms-holdings-portfolio',
            'kenetic-capital-portfolio',
            'alameda-research-portfolio',
            'multicoin-capital-portfolio',
            'okx-ventures-portfolio',
            'layer-1',
            'ftx-bankruptcy-estate',
            'sec-security-token',
            'alleged-sec-securities',
            'cmc-crypto-awards-2024',
        ],
        'tag-names': [
            'PoS',
            'Platform',
            'Solana Ecosystem',
            'CMS Holdings Portfolio',
            'Kenetic Capital Portfolio',
            'Alameda Research Portfolio',
            'Multicoin Capital Portfolio',
            'OKX Ventures Portfolio',
            'Layer 1',
            'FTX Bankruptcy Estate ',
            'SEC Security Token',
            'Alleged SEC Securities',
            'CMC Crypto Awards 2024',
        ],
        'tag-groups': [
            'ALGORITHM',
            'CATEGORY',
            'PLATFORM',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
            'CATEGORY',
        ],
        urls: {
            website: [Array],
            twitter: [Array],
            message_board: [Array],
            chat: [Array],
            facebook: [],
            explorer: [Array],
            reddit: [Array],
            technical_doc: [Array],
            source_code: [Array],
            announcement: [],
        },
        platform: null,
        date_added: '2020-04-10T00:00:00.000Z',
        twitter_username: 'solana',
        is_hidden: 0,
        date_launched: '2020-03-16T00:00:00.000Z',
        contract_address: [],
        self_reported_circulating_supply: null,
        self_reported_tags: null,
        self_reported_market_cap: null,
        infinite_supply: true,
    },
};
