export default {
    indexHeading: 'Upgrade Your Banking Experience Today.',
    indexButton1: 'Log in',
    indexButton2: 'Sign up',
    signUpTitle: "Let's get started!",
    signUpDescription:
        'Enter your phone number. We will send you a six-digit confirmation code there.',
    signUpHaveAccount: 'Already have an account? Log in',
    signInTitle: 'Welcome back',
    signInDescription: 'Enter the phone number associated with your account.',
    signInButton: 'Continue',
    authTitle: '6-digit code',
    authDescription: ['Code sent to ', ' unless you already have an account.'],
    homeAction1: 'Add money',
    homeAction2: 'Exchange',
    homeAction3: 'Details',
    homeAction4: 'More',
    homeSection1: 'Transactions',
    homeSection2: 'Widgets',
    homeNoTransaction: 'No transactions yet',
    viewMore: 'View More',
    cryptoTitle: 'Latest crypto',
    cryptoDetailAction1: 'Buy',
    cryptoDetailAction2: 'Receive',
    cryptoDetailOverviewTitle: 'Overview',
    cryptoDetailOverviewDescription:
        'Bitcoin is a decentralized digital currency, without a central bank or single administrator, that can be sent from user to user on the peer-to-peer bitcoin network without the need for intermediaries. Transactions are verified by network nodes through cryptography and recorded in a public distributed ledger called a blockchain.',
};
